// dashboard/app/actions/webrtc.ts
"use client";

import { supabase } from "@/lib/supabase-api";

export class WebRTCParentController {
  private peerConnection: RTCPeerConnection | null = null;
  private sessionId: string;
  private videoElementRef: React.RefObject<HTMLVideoElement>;

  /**
   * Initializes the WebRTC Controller.
   * @param sessionId The active UUID of the current Focus Session.
   * @param videoElementRef A React Ref pointing to the `<video>` element on the dashboard.
   */
  constructor(sessionId: string, videoElementRef: React.RefObject<HTMLVideoElement>) {
    this.sessionId = sessionId;
    this.videoElementRef = videoElementRef;
  }

  /**
   * Initiates the P2P connection sequence and triggers the Flutter 3-second ambush.
   */
  public async requestLiveVerification() {
    console.log("Initializing WebRTC Parent Node...");

    // 1. Initialize PeerConnection with standard free public STUNs
    this.peerConnection = new RTCPeerConnection({
      iceServers: [
        {
          urls: [
            'stun:stun.l.google.com:19302',
            'stun:stun1.l.google.com:19302'
          ]
        }
      ]
    });

    // 2. Handle incoming remote video track from the Flutter tablet
    this.peerConnection.ontrack = (event) => {
      console.log("Remote WebRTC track received from tablet.");
      
      if (this.videoElementRef.current) {
        // Pipe the incoming remote media track directly into the <video> tag
        if (event.streams && event.streams[0]) {
          this.videoElementRef.current.srcObject = event.streams[0];
        } else {
          this.videoElementRef.current.srcObject = new MediaStream([event.track]);
        }
        
        // Ensure browser policies are met for immediate playback
        this.videoElementRef.current.autoplay = true;
        this.videoElementRef.current.playsInline = true;
        this.videoElementRef.current.muted = true; // Required by modern browsers for autoPlay
      }
    };

    // 3. Serialize and push Parent ICE Candidates to Supabase
    this.peerConnection.onicecandidate = async (event) => {
      if (event.candidate) {
        await supabase.from('webrtc_signaling').insert({
          session_id: this.sessionId,
          type: 'candidate_parent',
          payload: event.candidate.toJSON()
        });
      }
    };

    // 4. Create and push the SDP Offer
    try {
      // We only want to receive media, not send it.
      const offer = await this.peerConnection.createOffer({
        offerToReceiveAudio: true,
        offerToReceiveVideo: true,
      });
      await this.peerConnection.setLocalDescription(offer);

      await supabase.from('webrtc_signaling').insert({
        session_id: this.sessionId,
        type: 'offer_parent',
        payload: {
          type: offer.type,
          sdp: offer.sdp
        }
      });
      
      console.log("Parent SDP Offer dispatched.");
    } catch (e) {
      console.error("Failed to generate Parent Offer:", e);
    }

    // 5. Sync Answers and Candidates from the Flutter Tablet via Supabase Realtime
    supabase
      .channel('public:webrtc_signaling_parent')
      .on('postgres_changes', {
        event: 'INSERT',
        schema: 'public',
        table: 'webrtc_signaling',
        filter: `session_id=eq.${this.sessionId}`
      }, async (payload) => {
        const record = payload.new;

        if (record.type === 'answer_tablet') {
          await this._handleAnswer(record.payload);
        } else if (record.type === 'candidate_tablet') {
          await this._handleRemoteCandidate(record.payload);
        }
      })
      .subscribe();
  }

  /**
   * Evaluates and sets the Remote SDP Answer generated by the Flutter engine.
   */
  private async _handleAnswer(answerPayload: any) {
    if (!this.peerConnection) return;
    try {
      const remoteDesc = new RTCSessionDescription(answerPayload);
      await this.peerConnection.setRemoteDescription(remoteDesc);
      console.log("Successfully set Remote Tablet SDP Answer.");
    } catch (e) {
      console.error("Error setting Remote Description:", e);
    }
  }

  /**
   * Appends ICE candidates generated by the tablet to the parent connection.
   */
  private async _handleRemoteCandidate(candidatePayload: any) {
    if (!this.peerConnection) return;
    try {
      const candidate = new RTCIceCandidate(candidatePayload);
      await this.peerConnection.addIceCandidate(candidate);
    } catch (e) {
      console.error("Error adding Remote ICE Candidate:", e);
    }
  }

  /**
   * Safely terminates the active P2P streaming session.
   */
  public disconnect() {
    this.peerConnection?.close();
    this.peerConnection = null;
    if (this.videoElementRef.current) {
        this.videoElementRef.current.srcObject = null;
    }
    supabase.removeAllChannels();
    console.log("WebRTC Node Disconnected.");
  }
}
